language: objective-c

cache:
- bundler
- cocoapods

install:
- bundle install
- bundle exec pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/trustbadge_iOS.xcworkspace -scheme trustbadge_iOS-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick

after_success: slather
